### ISSUE TITLE
Failure to identify platform name derails fastq creation

### ISSUE THREAD

**Issue by khoegenauer** [fls-bioinformatics-core/auto_process_ngs#156]
https://github.com/fls-bioinformatics-core/auto_process_ngs/blob/4659e2fd7c745acc69fe09c700517771458a92b2/auto_process_ngs/auto_processor.py#L1457

For anyone (me) whose sequencer ID is not included in the sequencer dictionary (bcftbx/platforms.py), IlluminaData.IlluminaRun() returns an exception.

Catch and grab platform name from metadata.info (manually set by user)?

**Comment by pjbriggs** [comment]
Hello @khoegenauer 

Thanks for filing this issue - I've made a start on some updates in PR #157 to try and address this, which should allow setting the platform explicitly either via the metadata as you suggest, or via a new `--platform` option on the `make_fastqs` command.

I'll add a note to this issue once I've merged the changes into the master branch as part of a new version of the package.

**Comment by pjbriggs** [comment]
@khoegenauer I've now merged this into a new version of the package (0.10.0), so if you reinstall/update the `genomics` package to the latest version (1.2.0) and then reinstall/update `auto_process_ngs`, you should be able to do either

    auto_process.py make_fastqs --platform=<PLATFORM> ...

or set the platform in the metadata file by manually editing or using e.g. `auto_process.py metadata --set platform=<PLATFORM>` before running the `make_fastqs` command.

So I'm going to close this issue, however if you try it and have problems then either reopen the issue or file a new one and I'll follow it up.
