### ISSUE TITLE
if I want to start with fastq file?how can I do ?

### ISSUE THREAD

**Issue by liaoshengyou** [fls-bioinformatics-core/auto_process_ngs#159]
hello, while I see this softwares, I have some questions, about this, I get my fastq data from seqcompany, and I have a meatadata like this. how can I start analysis with yoursoft.
metadata:
TCAGGTCGCCG N/A CI-1 Chip_ 1 A1 0 1 TRUE
GTTCGTACCGC N/A CI-1 Chip_ 1 A1 0 8 TRUE
TCGCTTGCCGT N/A CI-1 Chip_ 1 A1 0 11 TRUE
CCTCCGCCTGC N/A CI-2 Chip_ 2 A2 0 16 TRUE
CCATATACGAC N/A CI-2 Chip_ 2 A2 0 17 TRUE
TGCATGGCTCC N/A CI-2 Chip_ 2 A2 0 21 TRUE
CGGCGGAGCCA N/A CI-1 Chip_ 1 A1 0 30 TRUE
CCGTCCTCAGT N/A CI-1 Chip_ 1 A1 0 32 TRUE
TGGTACTATAT N/A CI-2 Chip_ 2 A2 0 36 TRUE
AGAATATCGTC N/A CI-2 Chip_ 2 A2 0 38 TRUE

**Comment by pjbriggs** [comment]
@liaoshengyou thanks for your interest in our software.

If you already have Fastq files then our pipeline is probably not what you need as it has a very limited analysis component which performs a few QC steps.

The documentation for our pipeline is also limited but should explain how to install and configure the software, so this would be the best place to start:
http://auto-process-ngs.readthedocs.io/en/latest/
If you have a specific problem with these then please get back in touch with more details.

However: I would suggest you investigate analysis software which are more appropriate for the type of experiment you have performed (e.g. RNA-seq, ChIP-seq). The BioStars website is a good place to start for general information:
https://www.biostars.org/

Please note that unfortunately I'm not able to help you with other software packages or other advice on the bioinformatics.

**Comment by liaoshengyou** [comment]
Thanks very much，I will use the fastq files after QC to align genome and count the UMI number for later analysis。
